# Generated by Django 4.2.2 on 2023-07-01 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_manager", "0003_alter_expense_cost_alter_expense_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="income_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
