# Generated by Django 4.2.2 on 2023-07-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_manager", "0004_alter_category_user"),
        ("budget_manager", "0004_alter_income_income_date"),
    ]

    operations = []
