# Generated by Django 4.2.2 on 2023-07-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget_manager", "0005_merge_20230702_0922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "amount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.income",
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_manager.expense",
                    ),
                ),
            ],
        ),
    ]
