# Generated by Django 4.2.2 on 2023-07-02 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_manager", "0006_alter_category_name_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
